#!/usr/bin/env bash
# pings an IP address passed as CLI argument 5times
# If no argument is passed display an error message
if [ $# -eq 1 ];
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
