#!/usr/bin/env bash
# Handling various signals
PID_FILE="/var/run/myscript.pid"
FILE_PID=$$
echo "$FILE_PID" > "$PID_FILE"
handle_sigterm() {
	echo "I hate the kill command"
	rm -r "$PID_FILE"
	exit 0
}

handle_sigquit() {
	rm -r "$PID_FILE"
	exit 0
}

handle_sigint() {
	echo "Y U no love me?!"
	exit 0
}

trap "handle_sigterm" SIGTERM
trap "handle_sigquit" SIGQUIT
trap "handle_sigint" SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
