#!/usr/bin/env bash
# Prints a different message on the 4th and 8th iteration
#+ NOTE: this loop is zero-indexed
COUNT=0
while [ $COUNT -lt 10 ]; do
	if [ $COUNT -eq 3 ]
	then
		echo "bad luck"
	elif [ $COUNT -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((COUNT++))
done
