#!/usr/bin/env bash
# prints "Best School" and custom messages on iteration 4, 9, 17
COUNT=1
while [ $COUNT -le 20 ]; do
	case $COUNT in
		4)
			echo $COUNT
			echo "bad luck from China"
			;;
		9)
			echo $COUNT
			echo "bad luck from Japan"
			;;
		17)
			echo $COUNT
			echo "bad luck from Italy"
			;;
		*)
			echo $COUNT
			;;
	esac
	((COUNT++));
done
