#!/usr/bin/env bash
# prints a clock 0-12hrs. for each hour it prins 1-59 mins
#+ We achieve this using the nested while loop only
HOUR=0
while [ $HOUR -le 12 ]; do
	echo "Hour: $HOUR"
	MINS=1
	while [ $MINS -le 59 ]; do
		echo "$MINS"
		((MINS++));
	done
	((HOUR++));
done
