#!/usr/bin/env bash
# lists a file and displays the names of the files after the firs dash
for file in *; do
	if [[ -f "$file" || -d "$file" ]] && [[ "$file" != .* ]]
	then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
